import { Beat, Event, BookingRoom } from '../types';

export const BEATS: Beat[] = [
  {
    id: '1',
    title: 'Atlanta Nights',
    producer: 'LoudHouse Beats',
    genre: 'Trap',
    bpm: 140,
    key: 'F Minor',
    duration: '3:24',
    price: { basic: 29.99, premium: 69.99, exclusive: 299.99 },
    tags: ['trap', 'hard', 'atlanta', 'dark'],
    plays: 12400,
    likes: 847,
    imageUrl: 'https://images.unsplash.com/photo-1598387181032-a3103a2db5b3?w=400',
    isFeatured: true,
    isNew: false,
  },
  {
    id: '2',
    title: 'Mercury Rising',
    producer: 'LoudHouse Beats',
    genre: 'R&B',
    bpm: 88,
    key: 'G Major',
    duration: '2:58',
    price: { basic: 24.99, premium: 59.99, exclusive: 249.99 },
    tags: ['r&b', 'smooth', 'melodic', 'vibes'],
    plays: 8900,
    likes: 623,
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    isFeatured: true,
    isNew: false,
  },
  {
    id: '3',
    title: 'Loud Frequency',
    producer: 'LoudHouse Beats',
    genre: 'Hip-Hop',
    bpm: 95,
    key: 'A Minor',
    duration: '3:12',
    price: { basic: 34.99, premium: 79.99, exclusive: 349.99 },
    tags: ['hip-hop', 'boom-bap', 'lyrical', 'classic'],
    plays: 15200,
    likes: 1102,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400',
    isFeatured: false,
    isNew: true,
  },
  {
    id: '4',
    title: 'Saturn Returns',
    producer: 'LoudHouse Beats',
    genre: 'Trap',
    bpm: 145,
    key: 'C Minor',
    duration: '2:44',
    price: { basic: 29.99, premium: 69.99, exclusive: 299.99 },
    tags: ['trap', 'space', 'ambient', 'drill'],
    plays: 7600,
    likes: 512,
    imageUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=400',
    isFeatured: false,
    isNew: true,
  },
  {
    id: '5',
    title: 'Peach State Anthem',
    producer: 'LoudHouse Beats',
    genre: 'Hip-Hop',
    bpm: 112,
    key: 'D Minor',
    duration: '3:08',
    price: { basic: 39.99, premium: 89.99, exclusive: 399.99 },
    tags: ['hip-hop', 'atlanta', 'anthem', 'club'],
    plays: 21000,
    likes: 1540,
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400',
    isFeatured: true,
    isNew: false,
  },
  {
    id: '6',
    title: 'Venus Trap',
    producer: 'LoudHouse Beats',
    genre: 'Trap/Soul',
    bpm: 130,
    key: 'E Minor',
    duration: '3:36',
    price: { basic: 34.99, premium: 79.99, exclusive: 349.99 },
    tags: ['trap', 'soul', 'melodic', 'emotional'],
    plays: 9800,
    likes: 745,
    imageUrl: 'https://images.unsplash.com/photo-1619983081563-430f63602796?w=400',
    isFeatured: false,
    isNew: false,
  },
  {
    id: '7',
    title: 'Midnight Session',
    producer: 'LoudHouse Beats',
    genre: 'R&B',
    bpm: 76,
    key: 'B Flat Major',
    duration: '4:02',
    price: { basic: 24.99, premium: 59.99, exclusive: 249.99 },
    tags: ['r&b', 'late night', 'smooth', 'chill'],
    plays: 6400,
    likes: 489,
    imageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=400',
    isFeatured: false,
    isNew: true,
  },
  {
    id: '8',
    title: 'Jupiter Wave',
    producer: 'LoudHouse Beats',
    genre: 'Afrobeats',
    bpm: 102,
    key: 'F Major',
    duration: '3:18',
    price: { basic: 29.99, premium: 69.99, exclusive: 299.99 },
    tags: ['afrobeats', 'dancehall', 'vibe', 'summer'],
    plays: 11300,
    likes: 892,
    imageUrl: 'https://images.unsplash.com/photo-1571266028243-d220c6a7c9b3?w=400',
    isFeatured: false,
    isNew: false,
  },
];

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Frequency Check – August Edition',
    date: 'August 15, 2026',
    time: '7:00 PM',
    location: 'LoudHouse Studios, Atlanta GA',
    description:
      'Our monthly artist showcase and competition. Emerging artists perform live for prizes, content creation opportunities, and the chance to level up their music career. Limited spots available to perform.',
    price: '$15 (Audience) / $25 (Performer)',
    category: 'showcase',
  },
  {
    id: '2',
    title: 'Date Night at the Studio',
    date: 'July 20, 2026',
    time: '6:00 PM',
    location: 'LoudHouse Studios, Atlanta GA',
    description:
      'Bring your partner for a unique music-making experience. Work with a professional producer, create an original song, and walk away with a memory you can actually replay.',
    price: '$149 per couple',
    category: 'date-night',
  },
  {
    id: '3',
    title: 'Producer Workshop: Mixing & Mastering',
    date: 'July 27, 2026',
    time: '2:00 PM',
    location: 'LoudHouse Studios, Atlanta GA',
    description:
      'An intensive hands-on workshop covering professional mixing and mastering techniques. Limited to 8 participants. All levels welcome.',
    price: '$75',
    category: 'workshop',
  },
  {
    id: '4',
    title: 'Frequency Check – September Edition',
    date: 'September 19, 2026',
    time: '7:00 PM',
    location: 'LoudHouse Studios, Atlanta GA',
    description:
      'Monthly artist showcase and competition highlighting emerging talent. Perform live for prizes, content, and industry connections.',
    price: '$15 (Audience) / $25 (Performer)',
    category: 'showcase',
  },
];

export const BOOKING_ROOMS: BookingRoom[] = [
  {
    id: '1',
    name: 'Studio A – Main Room',
    description:
      'Our flagship recording studio featuring top-of-the-line equipment, a spacious live room, and full isolation booth. Perfect for full band recordings, vocal sessions, and professional projects.',
    capacity: 8,
    hourlyRate: 75,
    features: [
      'SSL Mixing Console',
      'Pro Tools HDX',
      'Neumann U87 Mic',
      'Yamaha Grand Piano',
      'Full Isolation Booth',
      'Lounge Access',
    ],
  },
  {
    id: '2',
    name: 'Studio B – Production Suite',
    description:
      'Our production-focused suite built for beatmakers, mix engineers, and songwriters. Features a custom PC rig and extensive plugin library.',
    capacity: 4,
    hourlyRate: 55,
    features: [
      'Custom Production PC',
      'Ableton & Logic Pro',
      'Maschine MK3',
      'Native Instruments Suite',
      'Reference Monitors',
      'Comfort Seating',
    ],
  },
  {
    id: '3',
    name: 'Date Night Package',
    description:
      'A curated experience for couples or groups to create a song together under the guidance of a professional producer. Includes a full session, refreshments, and your finished track.',
    capacity: 4,
    hourlyRate: 149,
    features: [
      'Professional Producer',
      'Full Recording Session',
      'Complimentary Refreshments',
      'Finished Track Download',
      'Content Creation',
      '2 Hours Included',
    ],
  },
];

export const GENRES = ['All', 'Trap', 'R&B', 'Hip-Hop', 'Afrobeats', 'Trap/Soul', 'Drill'];
